### ISSUE TITLE
Ruby On Rails Forum - Image not rendering in footer

### ISSUE THREAD

**Issue by adgsenpai** [rails/website#76]
Hi, please sort out the footer for your Forum. It looks ugly when an image is not being rendered in a website.

![image](https://user-images.githubusercontent.com/45560312/198909021-201dae41-6fee-46a7-b632-ee7498bb3ccc.png)

![image](https://user-images.githubusercontent.com/45560312/198908987-fa94f5c9-aa96-4b2e-b884-fdf3cef033db.png)

![image](https://user-images.githubusercontent.com/45560312/198908994-76abff34-6003-4e91-a3dd-8fb0f7965f7d.png)

All the best!

**Comment by espen** [comment]
Doesn't look like this is applicable today.

**Comment by gregmolnar** [comment]
Thanks @espen ! It looks like this was fixed. I am closing it.

**Comment by adgsenpai** [comment]
![image](https://user-images.githubusercontent.com/45560312/218759380-86afca3c-01a9-48a2-8aae-dad6b5df318e.png)

I dont think this is fixed?
https://discuss.rubyonrails.org/t/why-memecached-is-more-popular-than-redis-for-rails-cache-store/81722/9

**Comment by gregmolnar** [comment]
Ah, @adgsenpai that is the community site, not the one in this repository. I will reopen this and look into how to fix that. Thanks!

**Comment by adgsenpai** [comment]
> Ah, @adgsenpai that is the community site, not the one in this repository. I will reopen this and look into how to fix that. Thanks!

Thank you!

**Comment by Sannitya-13** [comment]
I guess i can fix this issue please assign me this

**Comment by adgsenpai** [comment]
Seems to be fixed now @Sannitya-13 

![image](https://user-images.githubusercontent.com/45560312/227297068-20ebf724-0a45-4de4-aa07-ad9e7a0ba5fa.png)

LGTM, that footer is ugly and not centered but not as bad as before, I will close the issue as it is resolved.
